const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let marketData=[];
const demoData=(()=>{let out=[],p=980;for(let i=0;i<220;i++){const date=new Date(Date.now()-(219-i)*86400000).toISOString().slice(0,10);const drift=Math.sin(i/13)*4+(Math.random()-.46)*18;p=Math.max(200,p+drift);const o=p+(Math.random()-.5)*10,h=Math.max(o,p)+Math.random()*12,l=Math.min(o,p)-Math.random()*12,c=p+(Math.random()-.5)*6;out.push({date,open:o,high:h,low:l,close:c,volume:Math.round(15000+Math.random()*45000)});p=c}return out})();
marketData=demoData;
function normalizeSymbol(symbol,market=''){
  let s=String(symbol||'').trim().toUpperCase().replace(/\s+/g,'');
  if(market==='台股'||market==='ETF') s=s.replace(/\.(TW|TWO)$/,'');
  return s.replace(/[^A-Z0-9.\-]/g,'');
}
function normalizeWatch(list){
  const seen=new Set(),out=[];
  (Array.isArray(list)?list:[]).forEach(item=>{
    const market=String(item?.market||'台股');
    const symbol=normalizeSymbol(item?.symbol,market);
    if(!symbol)return;
    const key=`${market}|${symbol}`;
    if(seen.has(key))return;
    seen.add(key);out.push({symbol,market});
  });
  return out;
}
let watch=normalizeWatch(store.get('anx_watch',[{symbol:'2330',market:'台股'},{symbol:'AAPL',market:'美股'},{symbol:'0050',market:'ETF'}]));
store.set('anx_watch',watch);
let portfolio=store.get('anx_portfolio',[{symbol:'2330',weight:35,beta:1.05,vol:24},{symbol:'0050',weight:25,beta:0.92,vol:18},{symbol:'AAPL',weight:20,beta:1.18,vol:28},{symbol:'CASH',weight:20,beta:0,vol:0}]);
let journal=store.get('anx_journal',[]);
let settings=store.get('anx_settings',{riskPerTrade:1,maxPositions:8,stressDrop:20});
const planTemplate=[['08:20','盤前掃描','檢查指數、夜盤、重大新聞與觀察清單。'],['08:45','盤前劇本','標記支撐壓力、主要情境與禁止追價區。'],['09:00','開盤策略','前 15 分鐘觀察量價，不急著證明自己比市場聰明。'],['10:30','盤中調整','確認趨勢是否延續，調整停損與部位。'],['12:00','風險檢查','重新計算總曝險與單筆風險。'],['13:20','收盤策略','決定留倉、減碼或平倉。'],['15:30','收盤復盤','記錄交易、錯誤與隔日觀察名單。']];
let plan=store.get('anx_plan_'+new Date().toISOString().slice(0,10),planTemplate.map(x=>({time:x[0],title:x[1],desc:x[2],done:false})));
function fmt(n,d=2){return Number.isFinite(+n)?Number(n).toFixed(d):'-'}
function sma(data,n){if(data.length<n)return null;return data.slice(-n).reduce((a,b)=>a+b.close,0)/n}
function ema(vals,n){const k=2/(n+1);let e=vals[0];for(let i=1;i<vals.length;i++)e=vals[i]*k+e*(1-k);return e}
function rsi(data,n=14){if(data.length<=n)return 50;let g=0,l=0;for(let i=data.length-n;i<data.length;i++){let d=data[i].close-data[i-1].close;d>0?g+=d:l-=d}if(l===0)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function atr(data,n=14){if(data.length<=n)return 0;let x=[];for(let i=data.length-n;i<data.length;i++){const p=data[i-1].close,c=data[i];x.push(Math.max(c.high-c.low,Math.abs(c.high-p),Math.abs(c.low-p)))}return x.reduce((a,b)=>a+b,0)/x.length}
function macd(data){const v=data.map(x=>x.close);return ema(v.slice(-60),12)-ema(v.slice(-60),26)}
function supportResistance(data,n=20){const s=data.slice(-n);return{support:Math.min(...s.map(x=>x.low)),resistance:Math.max(...s.map(x=>x.high))}}
function trend(data=marketData){const m5=sma(data,5),m20=sma(data,20),m60=sma(data,60),c=data.at(-1).close;if(c>m20&&m20>m60)return'多頭';if(c<m20&&m20<m60)return'空頭';return'震盪'}
function calcSignal(data=marketData){const R=rsi(data),M=macd(data),T=trend(data);if(T==='多頭'&&R<72&&M>0)return'偏多';if(T==='空頭'&&R>28&&M<0)return'偏空';return'等待'}
function metrics(el,items){el.innerHTML=items.map(x=>`<div class="card metric"><div class="label">${x[0]}</div><div class="value ${x[2]||''}">${x[1]}</div></div>`).join('')}
function drawChart(data){const c=$('#priceChart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=50,arr=data.slice(-120),vals=arr.map(x=>x.close),min=Math.min(...vals),max=Math.max(...vals);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(140,162,186,.25)';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}ctx.strokeStyle='#33d6ff';ctx.lineWidth=3;ctx.beginPath();arr.forEach((d,i)=>{let x=p+(w-2*p)*i/(arr.length-1),y=h-p-(d.close-min)/(max-min||1)*(h-2*p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();const m20=[];for(let i=0;i<arr.length;i++){if(i<19)m20.push(null);else m20.push(arr.slice(i-19,i+1).reduce((a,b)=>a+b.close,0)/20)}ctx.strokeStyle='#70ffb1';ctx.lineWidth=2;ctx.beginPath();m20.forEach((v,i)=>{if(v==null)return;let x=p+(w-2*p)*i/(arr.length-1),y=h-p-(v-min)/(max-min||1)*(h-2*p);if(i===19)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke()}
function renderTech(){const c=marketData.at(-1).close,R=rsi(marketData),M=macd(marketData),A=atr(marketData),sr=supportResistance(marketData);metrics($('#techMetrics'),[['最後價',fmt(c)],['RSI(14)',fmt(R,1),R>70?'warning':R<30?'positive':''],['MACD',fmt(M),M>=0?'positive':'negative'],['ATR',fmt(A)]]);$('#techSignal').innerHTML=`<b>趨勢：</b>${trend()}<br><b>交易訊號：</b>${calcSignal()}<br><b>MA5 / MA20 / MA60：</b>${fmt(sma(marketData,5))} / ${fmt(sma(marketData,20))} / ${fmt(sma(marketData,60))}<br><b>解讀：</b>${R>70?'RSI 偏熱，避免追價。':R<30?'RSI 偏低，留意反彈但需確認趨勢。':'動能位於中性區，可搭配均線與量價確認。'}`;$('#srBox').innerHTML=`20 日支撐：<b>${fmt(sr.support)}</b><br>20 日壓力：<b>${fmt(sr.resistance)}</b><br>距離支撐：${fmt((c-sr.support)/c*100,1)}%<br>距離壓力：${fmt((sr.resistance-c)/c*100,1)}%`;drawChart(marketData)}
function pseudoPrice(sym){let h=[...sym].reduce((a,c)=>a+c.charCodeAt(0),0);return 50+(h%1200)+Math.sin(Date.now()/86400000+h)*8}
function scanRows(){const base=marketData.at(-1).close,A=atr(marketData),T=trend(),R=rsi(marketData),sr=supportResistance(marketData);$('#scanTable').innerHTML=watch.map((w,i)=>{const px=i===0?base:pseudoPrice(w.symbol),stop=px-Math.max(A,px*.03),target=px+Math.max(A*2,px*.06),rr=(target-px)/(px-stop);return`<tr><td>${w.symbol}<br><small>${w.market}</small></td><td>${T}</td><td>${fmt(px)}</td><td>${fmt(target)}</td><td>${fmt(stop)}</td><td>1:${fmt(rr,1)}</td><td>RSI ${fmt(R,0)}、${T}、20日區間 ${fmt(sr.support)}-${fmt(sr.resistance)}</td><td><button class="ghost remove-watch" data-index="${i}">刪除</button></td></tr>`}).join('');$$('.remove-watch').forEach(b=>b.onclick=()=>removeWatch(+b.dataset.index));metrics($('#marketMetrics'),[['觀察標的',watch.length],['多空狀態',T,T==='多頭'?'positive':T==='空頭'?'negative':'warning'],['RSI',fmt(R,1)],['ATR',fmt(A)]])}
function renderWatch(){const T=trend(),R=rsi(marketData),sig=calcSignal();$('#watchTable').innerHTML=watch.map((w,i)=>`<tr><td>${w.symbol}</td><td>${w.market}</td><td>${fmt(i===0?marketData.at(-1).close:pseudoPrice(w.symbol))}</td><td>${fmt(R,1)}</td><td>${T}</td><td>${sig}</td><td><button class="ghost remove-watch-dashboard" data-index="${i}">刪除</button></td></tr>`).join('');$$('.remove-watch-dashboard').forEach(b=>b.onclick=()=>removeWatch(+b.dataset.index))}
function removeWatch(index){if(index<0||index>=watch.length)return;watch.splice(index,1);store.set('anx_watch',watch);scanRows();renderDashboard()}
function analyzeNews(){const t=$('#newsText').value.trim(),target=$('#newsTarget').value.trim()||'此標的';if(!t)return $('#newsResult').textContent='請先貼上新聞內容。';const pos=['成長','上修','獲利','擴產','訂單','創高','降息','回購','合作','突破'],neg=['下修','虧損','制裁','調查','事故','衰退','減產','違約','裁員','跌價'];let s=0;pos.forEach(x=>{if(t.includes(x))s++});neg.forEach(x=>{if(t.includes(x))s--});let bias=s>0?'偏正向':s<0?'偏負向':'中性';$('#newsResult').innerHTML=`<b>${target}</b><br>事件傾向：<b>${bias}</b><br>短期：可能先反映情緒與預期，需觀察量價是否確認。<br>中期：重點在營收、毛利、資本支出與產業供需是否真的改變。<br>交易處理：${s>0?'避免追高，等回測支撐或量價確認。':s<0?'降低曝險、觀察支撐失守與停損。':'先等待市場給方向，不因單一標題硬做。'}<br>風險：新聞可能已提前反映，且文字情緒不等於基本面結果。`}
function runBacktest(){const type=$('#strategy').value,f=+$(`#fastPeriod`).value,s=+$(`#slowPeriod`).value,fee=+$(`#feeRate`).value;let trades=[],entry=null;for(let i=Math.max(s,21);i<marketData.length;i++){const d=marketData[i],hist=marketData.slice(0,i+1);let buy=false,sell=false;if(type==='ma'){buy=sma(hist,f)>sma(hist,s)&&sma(marketData.slice(0,i),f)<=sma(marketData.slice(0,i),s);sell=entry&&sma(hist,f)<sma(hist,s)}else if(type==='rsi'){buy=rsi(hist)<30; sell=entry&&rsi(hist)>55}else{const prev=marketData.slice(i-20,i),hh=Math.max(...prev.map(x=>x.high)),ll=Math.min(...prev.map(x=>x.low));buy=d.close>hh;sell=entry&&d.close<ll}if(!entry&&buy)entry={date:d.date,price:d.close};else if(entry&&sell){const ret=(d.close*(1-fee)-entry.price*(1+fee))/(entry.price*(1+fee));trades.push({...entry,exitDate:d.date,exit:d.close,ret});entry=null}}if(entry){const d=marketData.at(-1),ret=(d.close*(1-fee)-entry.price*(1+fee))/(entry.price*(1+fee));trades.push({...entry,exitDate:d.date,exit:d.close,ret})}const wins=trades.filter(x=>x.ret>0),loss=trades.filter(x=>x.ret<=0),gp=wins.reduce((a,b)=>a+b.ret,0),gl=Math.abs(loss.reduce((a,b)=>a+b.ret,0));let eq=1,peak=1,mdd=0;trades.forEach(x=>{eq*=1+x.ret;peak=Math.max(peak,eq);mdd=Math.min(mdd,(eq-peak)/peak)});metrics($('#backtestMetrics'),[['交易次數',trades.length],['勝率',trades.length?fmt(wins.length/trades.length*100,1)+'%':'-'],['獲利因子',gl?fmt(gp/gl,2):gp>0?'∞':'-'],['最大回撤',fmt(Math.abs(mdd)*100,1)+'%','negative']]);$('#tradeTable').innerHTML=trades.map(x=>`<tr><td>${x.date}</td><td>${fmt(x.price)}</td><td>${x.exitDate}</td><td>${fmt(x.exit)}</td><td class="${x.ret>=0?'positive':'negative'}">${fmt(x.ret*100,2)}%</td><td>${x.ret>=0?'獲利':'虧損'}</td></tr>`).join('')}
function renderPortfolio(){const box=$('#positions');box.innerHTML=portfolio.map((p,i)=>`<div class="position-row"><input value="${p.symbol}" data-i="${i}" data-k="symbol"><input type="number" value="${p.weight}" data-i="${i}" data-k="weight" placeholder="配置%"><input type="number" step=".01" value="${p.beta}" data-i="${i}" data-k="beta" placeholder="Beta"><input type="number" step=".1" value="${p.vol||20}" data-i="${i}" data-k="vol" placeholder="波動%"><button class="ghost delpos" data-i="${i}">刪除</button></div>`).join('');$$('#positions input').forEach(x=>x.onchange=()=>{portfolio[x.dataset.i][x.dataset.k]=x.dataset.k==='symbol'?x.value:+x.value;store.set('anx_portfolio',portfolio)});$$('.delpos').forEach(b=>b.onclick=()=>{portfolio.splice(+b.dataset.i,1);store.set('anx_portfolio',portfolio);renderPortfolio()})}
function analyzePortfolio(){const total=portfolio.reduce((a,b)=>a+(+b.weight||0),0),beta=portfolio.reduce((a,b)=>a+(+b.weight||0)*(+b.beta||0),0)/(total||1),max=Math.max(0,...portfolio.map(x=>+x.weight||0)),stress=beta*(+settings.stressDrop||20),vol=Math.sqrt(portfolio.reduce((a,b)=>a+Math.pow((+b.weight||0)/100*(+b.vol||0),2),0));metrics($('#portfolioMetrics'),[['配置合計',fmt(total,1)+'%',total>102?'warning':''],['組合 Beta',fmt(beta,2)],['最大單一部位',fmt(max,1)+'%',max>35?'warning':''],[`市場-${settings.stressDrop}%壓測`,fmt(stress,1)+'%','negative']]);let msg=[];if(total>100)msg.push('總配置超過 100%，代表存在槓桿或輸入需要修正。');if(max>35)msg.push('單一部位偏高，個股事件可能主導整體損益。');if(beta>1.2)msg.push('組合對市場波動較敏感。');if(vol>20)msg.push('名目波動度偏高，可增加低波動或現金部位。');if(!msg.length)msg.push('配置目前沒有明顯單點風險，但仍需注意產業相關性與黑天鵝。');$('#portfolioResult').innerHTML=msg.map(x=>'• '+x).join('<br>')+'<br><b>再平衡原則：</b>單一持股盡量避免過度集中，並用停損、現金與低相關資產降低尾端風險。'}
function renderJournal(){const rows=journal.map(x=>{const r=(x.side==='放空'?(x.entry-x.exit):(x.exit-x.entry))/x.entry;return{...x,r}});$('#journalTable').innerHTML=rows.map(x=>`<tr><td>${x.date}</td><td>${x.symbol}</td><td>${x.side}</td><td>${fmt(x.entry)}</td><td>${fmt(x.exit)}</td><td class="${x.r>=0?'positive':'negative'}">${fmt(x.r*100,2)}%</td><td>${x.note||''}</td></tr>`).join('');const wins=rows.filter(x=>x.r>0),avg=rows.length?rows.reduce((a,b)=>a+b.r,0)/rows.length:0;metrics($('#journalMetrics'),[['交易筆數',rows.length],['勝率',rows.length?fmt(wins.length/rows.length*100,1)+'%':'-'],['平均報酬',fmt(avg*100,2)+'%',avg>=0?'positive':'negative'],['最大單筆虧損',rows.length?fmt(Math.min(...rows.map(x=>x.r))*100,2)+'%':'-','negative']]);let notes=rows.map(x=>x.note||'').join(' '),issues=[];if(/追高|FOMO|怕錯過/i.test(notes))issues.push('有追價/FOMO 紀錄');if(/沒停損|凹單|加碼攤平/i.test(notes))issues.push('有停損紀律問題');if(/情緒|生氣|報復/i.test(notes))issues.push('有情緒交易跡象');$('#journalAnalysis').innerHTML=(issues.length?issues.map(x=>'• '+x).join('<br>'):'目前沒有從文字筆記抓到明顯重複錯誤。')+'<br><b>3 條紀律：</b>進場前先定停損；單筆風險固定；不因上一筆盈虧改變下一筆規則。'}
function renderPlan(){const box=$('#planList');box.innerHTML=plan.map((x,i)=>`<div class="timeline-item ${x.done?'done':''}"><div><b>${x.time}</b></div><input type="checkbox" data-i="${i}" ${x.done?'checked':''}><div><b>${x.title}</b><div class="hint">${x.desc}</div></div></div>`).join('');$$('#planList input').forEach(c=>c.onchange=()=>{plan[c.dataset.i].done=c.checked;store.set('anx_plan_'+new Date().toISOString().slice(0,10),plan);renderPlan();renderDashboard()})}
function renderDashboard(){renderWatch();const done=plan.filter(x=>x.done).length;metrics($('#dashboardMetrics'),[['最後價',fmt(marketData.at(-1).close)],['趨勢',trend(),trend()==='多頭'?'positive':trend()==='空頭'?'negative':'warning'],['交易訊號',calcSignal()],['今日計畫',`${done}/${plan.length}`]]);$('#marketSummary').innerHTML=`目前趨勢：<b>${trend()}</b><br>RSI：${fmt(rsi(marketData),1)}<br>MACD：${fmt(macd(marketData))}<br>ATR：${fmt(atr(marketData))}`;$('#riskSummary').innerHTML=`單筆最大風險：<b>${settings.riskPerTrade}%</b><br>最大持倉數：${settings.maxPositions}<br>壓力測試：市場下跌 ${settings.stressDrop}%<br>觀察清單：${watch.length} 檔`}
function parseCSV(txt){const lines=txt.trim().split(/\r?\n/),h=lines.shift().split(',').map(x=>x.trim().toLowerCase());const ix=k=>h.indexOf(k);return lines.map(l=>{const a=l.split(',');return{date:a[ix('date')],open:+a[ix('open')],high:+a[ix('high')],low:+a[ix('low')],close:+a[ix('close')],volume:+a[ix('volume')]}}).filter(x=>x.date&&Number.isFinite(x.close)).sort((a,b)=>a.date.localeCompare(b.date))}
function backup(){return{watch,portfolio,journal,settings,plan,marketData}}
function init(){renderTech();scanRows();renderPortfolio();analyzePortfolio();renderJournal();renderPlan();renderDashboard();$('#riskPerTrade').value=settings.riskPerTrade;$('#maxPositions').value=settings.maxPositions;$('#stressDrop').value=settings.stressDrop;$('#jDate').value=new Date().toISOString().slice(0,10)}
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
$('#runScan').onclick=scanRows;$('#refreshAll').onclick=init;$('#analyzeTech').onclick=()=>{renderTech();renderDashboard()};$('#useDemo').onclick=()=>{marketData=demoData;renderTech();renderDashboard()};
$('#addScan').onclick=()=>{
  const market=$('#scanMarket').value,symbol=normalizeSymbol($('#scanSymbol').value,market);
  if(!symbol)return alert('請輸入股票代號。');
  const exists=watch.some(w=>w.market===market&&w.symbol===symbol);
  if(exists)return alert(`${symbol} 已經在「${market}」觀察清單中，不會重複加入。`);
  watch.push({symbol,market});store.set('anx_watch',watch);$('#scanSymbol').value=symbol;scanRows();renderDashboard();
};$('#clearWatch').onclick=()=>{if(confirm('確定清空觀察清單？')){watch=[];store.set('anx_watch',watch);scanRows();renderDashboard()}};
$('#csvInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const d=parseCSV(r.result);if(d.length<30)return alert('CSV 資料不足，至少建議 30 筆。');marketData=d;renderTech();renderDashboard();alert(`已匯入 ${d.length} 筆資料`)};r.readAsText(f)};
$('#analyzeNews').onclick=analyzeNews;$('#runBacktest').onclick=runBacktest;
$('#addPosition').onclick=()=>{portfolio.push({symbol:'NEW',weight:10,beta:1,vol:20});store.set('anx_portfolio',portfolio);renderPortfolio()};$('#resetPortfolio').onclick=()=>{portfolio=[{symbol:'2330',weight:40,beta:1.05,vol:24},{symbol:'0050',weight:30,beta:.92,vol:18},{symbol:'CASH',weight:30,beta:0,vol:0}];store.set('anx_portfolio',portfolio);renderPortfolio();analyzePortfolio()};$('#analyzePortfolio').onclick=analyzePortfolio;
$('#saveTrade').onclick=()=>{const x={symbol:$('#jSymbol').value.trim().toUpperCase(),side:$('#jSide').value,entry:+$('#jEntry').value,exit:+$('#jExit').value,qty:+$('#jQty').value,date:$('#jDate').value,note:$('#jNote').value.trim()};if(!x.symbol||!x.entry||!x.exit||!x.date)return alert('請填完整交易資料。');journal.unshift(x);store.set('anx_journal',journal);renderJournal()};$('#clearJournal').onclick=()=>{if(confirm('確定清空交易日誌？')){journal=[];store.set('anx_journal',journal);renderJournal()}};
$('#resetPlan').onclick=()=>{plan=planTemplate.map(x=>({time:x[0],title:x[1],desc:x[2],done:false}));store.set('anx_plan_'+new Date().toISOString().slice(0,10),plan);renderPlan();renderDashboard()};
$('#saveSettings').onclick=()=>{settings={riskPerTrade:+$('#riskPerTrade').value,maxPositions:+$('#maxPositions').value,stressDrop:+$('#stressDrop').value};store.set('anx_settings',settings);renderDashboard();analyzePortfolio();alert('設定已儲存')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(backup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ApexNexus-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.watch)watch=normalizeWatch(d.watch);if(d.portfolio)portfolio=d.portfolio;if(d.journal)journal=d.journal;if(d.settings)settings=d.settings;if(d.plan)plan=d.plan;if(d.marketData?.length)marketData=d.marketData;store.set('anx_watch',watch);store.set('anx_portfolio',portfolio);store.set('anx_journal',journal);store.set('anx_settings',settings);store.set('anx_plan_'+new Date().toISOString().slice(0,10),plan);init();alert('備份匯入完成')}catch{alert('JSON 格式錯誤')}};r.readAsText(f)};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});init();
